# -*- coding: utf-8 -*-
"""DFL-LeNet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmZ5HWhKam_t9QMCk1xY1kOXfzrrnxeO

## DFL with LeNet on DNA Sequence Dataset

By: Sk. Tanzir Mehedi
"""

import urllib.request

def download_url(url, save_as):
    response = urllib.request.urlopen(url)
    data = response.read()
    file = open(save_as, 'wb')
    file.write(data)
    file.close()
    response.close()
    
def read_binary_file(file):
    f = open(file,'rb')
    block = f.read()
    return block.decode('utf-16')

def split_text_in_lines(text):
    return text.split('\r\n')

def split_by_tabs(line):
    return line.split('\t')

names_link = 'https://raw.githubusercontent.com/tanzirmehedi/Deep-Federated-Learning/main/preprocessedDNASequenceDataset.names'
data_link = 'https://raw.githubusercontent.com/tanzirmehedi/Deep-Federated-Learning/main/preprocessedDNASequenceDataset.data'

diagnosis_names = 'preprocessedDNASequenceDataset.names'
diagnosis_data = 'preprocessedDNASequenceDataset.data'
download_url(names_link, diagnosis_names)
download_url(data_link, diagnosis_data)

import numpy as np

def parse_double(field):
    field = field.replace(',', '.')
    return float(field)

def parse_boolean(field):
    return 1. if field == 'yes' else 0.

def read_np_array(file = diagnosis_data):
    text = read_binary_file(file)
    lines = split_text_in_lines(text)
    rows = []
    for line in lines:
        if line == '': continue
        line = line.replace('\r\n', '')
        fields = split_by_tabs(line)
        row = []
        j = 0
        for field in fields:
            value = parse_double(field) if j == 0 else parse_boolean(field)
            row.append(value)
            j += 1
        rows.append(row)
    matrix = np.array(rows, dtype = np.float32)
    return matrix

matrix = read_np_array()
matrix

n_samples, n_dimensions = matrix.shape
print(n_samples)
print(n_dimensions)

def get_random_indexes(n):
    indexes = list(range(n))
    random_indexes = []
    for i in range(n):
        r = np.random.randint(len(indexes))
        random_indexes.append(indexes.pop(r))
    return random_indexes

def get_indexes_for_2_datasets(n, training = 80):
    indexes = get_random_indexes(n)
    train = int(training / 100. * n)
    return indexes[:train], indexes[train:]

matrix = read_np_array()
n_samples, n_dimensions = matrix.shape

train_indexes, test_indexes = get_indexes_for_2_datasets(n_samples)
train_data = matrix[train_indexes]
test_data = matrix[test_indexes]

def print_dataset(name, data):
    print('Dataset {}. Shape: {}'.format(name, data.shape))
    print(data)

print(len(train_data))
print(len(test_data))
print(train_indexes)
print(test_indexes)

print_dataset('Train', train_data)

print_dataset('Test', test_data)

import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

input_size = 64
learning_rate = 0.01
num_iterations = 1000

class LogisticRegression(torch.nn.Module):

    def __init__(self):
        super(LogisticRegression, self).__init__()
        self.linear = torch.nn.Linear(input_size, 1)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

# Commented out IPython magic to ensure Python compatibility.
def decide(y):
    return 1. if y >= 0.5 else 0.

decide_vectorized = np.vectorize(decide)

to_percent = lambda x: '{:.2f}%'.format(x)

def compute_accuracy(model, input, output):
    prediction = model(input).data.numpy()[:, 0]
    n_samples = prediction.shape[0] + 0.
    prediction = decide_vectorized(prediction)
    equal = prediction == output.data.numpy()
    return 100. * equal.sum() / n_samples

def get_input_and_output(data):
    input = Variable(torch.tensor(data[:, :6], dtype = torch.float32))
    output = Variable(torch.tensor(data[:, 6], dtype = torch.float32))
    #output = Variable(torch.tensor(data[:, 6], dtype = torch.float32)[..., None])

    return input, output

input, output= get_input_and_output(train_data)
test_input, test_output = get_input_and_output(test_data)

import matplotlib.pyplot as plt
# %matplotlib inline

DFL_title = 'DFL with LeNet on DNA Sequence Dataset'


def plot_graphs(DFL_title, losses, accuracies):
    plt.plot(losses)
    plt.title(f"{DFL_title} - Training Loss")
    plt.xlabel("Iterations")
    plt.ylabel("Training Loss")
    plt.show()
    plt.plot(accuracies)
    plt.title(f"{DFL_title} - Training Accuracy")
    plt.xlabel("Iterations")
    plt.ylabel("Training Accuracy (Percent %)")
    plt.show()
    
def train_model(DFL_title, input, output, test_input, test_output):
    model = LogisticRegression()
    criterion = torch.nn.BCELoss(size_average=True)
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  
    losses = []
    accuracies = []
    n_samples, _ = input.shape
    for iteration in range(num_iterations):
            optimizer.zero_grad()
            prediction = model(input)
            loss = criterion(prediction, output)
            loss.backward()
            optimizer.step()
            if iteration % 500 == 0:
                train_acc = compute_accuracy(model, input, output)
                train_loss = loss.item()
                losses.append(train_loss)
                accuracies.append(train_acc)
                print('iteration={}, loss={:.4f}, train_acc={}'.format(iteration, train_loss, to_percent(train_acc)))
    plot_graphs(DFL_title, losses, accuracies)
    test_acc = compute_accuracy(model, test_input, test_output)
    print('\nTesting Accuracy = {}'.format(to_percent(test_acc)))
    return model

model = train_model(DFL_title, input, output, test_input, test_output)

#pip install syft==0.2.9

import syft as sy
import torch as th
hook = sy.TorchHook(th)
from torch import nn, optim

local_client_devices = 6
client_devicess = []
for i in range(local_client_devices):
    local_client_devices_name = 'client_devices{}'.format(i)
    client_devices = sy.VirtualWorker(hook, id = local_client_devices_name)
    print(client_devices)
    print(str(client_devices._objects))
    client_devicess.append(client_devices)
secure_worker = sy.VirtualWorker(hook, id="secure_worker")
print(secure_worker)
print(secure_worker._objects)

def get_workers_names(workers):
    return [worker.id for worker in workers]

def add_and_print_workers(worker, workers):
    print('workers of {} = {}'.format(worker.id, get_workers_names(workers)))
    worker.add_workers(workers)

for i in range(local_client_devices):
    workers = [client_devicess[i2] for i2 in range(local_client_devices) if i2 != i] + [secure_worker]
    add_and_print_workers(client_devicess[i], workers)
add_and_print_workers(secure_worker, client_devicess)

n_samples = train_data.shape[0]
print(n_samples)
print(local_client_devices)
samples_per_client_devices = int((n_samples + 0.5) / local_client_devices)
print(samples_per_client_devices)

client_devices_features = []
client_devices_targets = []

train_data = th.tensor(train_data, dtype = torch.float32, requires_grad=True)
train_data

for i in range(local_client_devices):
    train_data2 = train_data[i * samples_per_client_devices:(i + 1) * samples_per_client_devices].clone().detach().requires_grad_(True)
    features = train_data2[:, :6].clone().detach().requires_grad_(True)
    print(features)
    targets = train_data2[:, 6][:, None].clone().detach() 
    print(targets)
    client_devices_features.append(features.send(client_devicess[i]))
    print(client_devices_features)
    client_devices_targets.append(targets.send(client_devicess[i]))
    print(client_devices_features)

print(model)

def plot_federated_graphs(DFL_title, losses, accuracies):
    for i in range(local_client_devices):
        plt.plot(losses[i], label=f'client_devices {i}')
    legend = plt.legend(loc='upper right', shadow=True)
    plt.title(f"{DFL_title} - Training Loss")
    plt.xlabel("Iterations")
    plt.ylabel("Training Loss")
    plt.show()
    for i in range(local_client_devices):
        plt.plot(accuracies[i], label=f'client_devices {i}')
    legend = plt.legend(loc='lower right', shadow=True)
    plt.title(f"{DFL_title} - Training Accuracy")
    plt.xlabel("Iterations")
    plt.ylabel("Training Accuracy (Percent %)")
    plt.show()
    
def compute_federated_accuracy(model, input, output):
    prediction = model(input)
    n_samples = prediction.shape[0]
    s = 0.
    for i in range(n_samples):
        p = 1. if prediction[i] >= 0.5 else 0.
        e = 1. if p == output[i] else 0.
        s += e
    return 100. * s / n_samples

iterations = 1000 #2000
worker_iterations = 8

def federated_learning(DFL_title, client_devices_features, client_devices_targets, test_input, test_output):
    model = LogisticRegression()
    criterion = torch.nn.BCELoss(size_average=True)
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  
    losses = [[] for i in range(local_client_devices)]
    accuracies = [[] for i in range(local_client_devices)]
    for iteration in range(iterations):
        models = [model.copy().send(client_devicess[i]) for i in range(local_client_devices)]
        optimizers = [torch.optim.SGD(params = models[i].parameters(), lr = learning_rate) for i in range(local_client_devices)]
        for worker_iteration in range(worker_iterations):
            last_losses = []
            for i in range(local_client_devices):
                optimizers[i].zero_grad()
                prediction = models[i](client_devices_features[i])
                loss = criterion(prediction, client_devices_targets[i])
                loss.backward()
                optimizers[i].step()
                loss = loss.get().data.item()
                last_losses.append(loss)
        for i in range(local_client_devices):
            losses[i].append(last_losses[i])
            train_acc = compute_federated_accuracy(models[i], client_devices_features[i], client_devices_targets[i])
            accuracies[i].append(train_acc)
            models[i].move(secure_worker)
        with th.no_grad():
            avg_weight = sum([models[i].linear.weight.data for i in range(local_client_devices)]) / local_client_devices
            model.linear.weight.set_(avg_weight.get())
            avg_bias = sum([models[i].linear.bias.data for i in range(local_client_devices)]) / local_client_devices
            model.linear.bias.set_(avg_bias.get())
        if iteration % 100 == 0:
            losses_str = ['{:.4f}'.format(losses[i][-1]) for i in range(local_client_devices)]
            accuracies_str = [to_percent(accuracies[i][-1]) for i in range(local_client_devices)]
            print('Iteration={}, losses={}, accuracies={}'.format(iteration, losses_str, accuracies_str))
    plot_federated_graphs(DFL_title, losses, accuracies)
    test_acc = compute_accuracy(model, test_input, test_output)
    print('\nTesting Accuracy = {}'.format(to_percent(test_acc)))
    return model

model = federated_learning(DFL_title, client_devices_features, client_devices_targets, test_input, test_output)